services:
  vocabularium:
    build:
      context: .
      dockerfile: ./deployment/server/Dockerfile
    container_name: vocabularium
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      COLLATINUS_LANGUAGE: ${COLLATINUS_LANGUAGE}
      DB_URL: ${DB_URL}
    networks:
      - vocabularium
    ports:
      - "4321:4321"
    restart: always
  database:
    build:
      context: ./deployment/database
    container_name: database
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PRELOAD_SPQR: ${PRELOAD_SPQR}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-h", "localhost"]
      interval: 1s
      retries: 999999
      start_period: 1s
    networks:
      - vocabularium
    ports:
      - 5433:5432
    restart: always
    volumes:
      - database:/var/lib/postgresql/data

networks:
  vocabularium:

volumes:
  database:
